<?xml version="1.0" encoding="UTF-8"?>
<!--pom stores all project related information-->

<!--project tag - root tag of the pom-->
<!--three lines - tells rules about the schema design of pom ,all tags which are allowed-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">


<!--    pom version is told by model version , not tell the maven version-->
    <modelVersion>4.0.0</modelVersion>


<!--    uniquely identify the project-->
<!--    group id - (nomenclature)domain name reversed (no other jar files in internet of this name)-->
    <groupId>org.example</groupId>

<!--  project name -->
    <artifactId>springlecture3</artifactId>

<!--   experimental phase-->
    <version>1.0-SNAPSHOT ${author.name}</version> <!-- can call key value pair using ${} -->


    <packaging>jar </packaging>  <!-- can be jar or war packages-->



    <dependencies> <!-- each jar file have group id , artifact is and versions which we download from internet ,we dont need to remeber thier names of jar file we can just - seach it in maven repo -->

        <!-- Source: https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>9.7.0</version>
            <scope>compile</scope>  <!-- when thi s code will be required - in compile phase-->
        </dependency> <!-- these dependancy - get store in local cache, and also all transitive dependencies get downloaded-->

    </dependencies>
    <properties>
<!--        key value pair -->
<!--        any key can be made-->
        <author.name>richa</author.name>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>